### ISSUE TITLE
Confusion about Angular Syntax within AngularJS 

### ISSUE THREAD

**Issue by rit** [ExLibrisGroup/primo-explore-package#14]
The use of parentheses for event binding like this line:
`<prm-search-bar (search-event)="prmSearch.onSearchBarSearchEvent()">`
is Angular 4+ syntax. 

How is the use of that syntax made possible in AngularJS 1.x?

**Comment by noamamit92** [comment]
The code you are referencing is an example taken from our source code - to explain the concept of angulaJs components.

You can use Angular 4+ syntax in angularJs application if you use decorators such as:

https://github.com/ngParty/ng-metadata

but this is not really related to this project directly
