### ISSUE TITLE
Problems when using email templates with <prm-service-details> component

### ISSUE THREAD

**Issue by rochpaul** [ExLibrisGroup/primo-explore-package#18]
Hi,
our institute experiment the new html template feature in primo november release 2019. 
I'm interested to use the advantages of prm-service-details component to provide the same details in email as
in the full view.

I have followed your example in https://github.com/ExLibrisGroup/primo-explore-package/blob/master/help_files/email_en_US_Details.html

I have recognized two problems:

**1** The details will be shown only in email outgoing from email action in full view 
=> There is not the same result with email action in result list view.
Is there a possibility to use this component outside of full view context?
And if not, is there a possibilty to inject ServiceDetailsService in the own angularjs implementation? As i understand the whole parsing process for items to show the details in full view is implemented via this service.

**2** How is the **[is-email]="true"** Attribute in prm-service-details to be understood?
Unfortunately the details component are not adjusted for the email ? The pnx values are redundant as text and link in the mail.

**Comment by noamamit92** [comment]
@rochpaul  - The prm-service-details is not yet supported to use in an email templates and not documented in:

https://github.com/ExLibrisGroup/primo-explore-package/blob/master/VIEW_CODE/html/README.md

We do have plans to add support by using the [is-email]="true" - but that is not available yet.
