### ISSUE TITLE
How to override templates to insert a custom header?

### ISSUE THREAD

**Issue by gquach** [ExLibrisGroup/primo-explore-package#3]
I was wondering how we can override the default New Primo template (`components/primoExplore/primo-explore-main.html`) in order to insert our own custom header?

For example, we wish to insert a `<div id="slnsw-nav-bar">` just before the `<prm-topbar>` element.

I thought we would be able to do this by setting `$templateCache` for "`components/primoExplore/primo-explore-main.html`", but it seems this doesn't work -- if you use `console.log` to output the value of `$templateCache.get()`, it appears to be undefined.

Using `$templateCache.put()` in an attempt to change the template does not seem to do anything.

Here's the contents of our `custom.js` file:

```
(function () {
    'use strict';

    var app = angular.module('viewCustom', ['angularLoad']);

    app.component('prmLogoAfter', {
        template: '<div flex show-gt-sm id="prm-logo-after-content"><h1>Catalogue</h1></div>'
    });


    app.run(['$templateCache', function($templateCache) {
      console.log($templateCache.get('components/primoExplore/primo-explore-main.html'));

      $templateCache.put('components/primoExplore/primo-explore-main.html',
        '<div layout="column" class="header topbar-wrapper relative-position">' + '\n' +
        '  <div id="slnsw-nav-bar">' + '\n' +
        '    <a class="slnsw-link" href="http://www.sl.nsw.gov.au/" title="Back to the State Library of NSW site"><img class="slnsw-logo" src="custom/SLNSW/img/slnsw-logo.png" alt="State Library of NSW logo"></a>' + '\n' +
        '  </div>' + '\n' +
        '  <prm-topbar></prm-topbar>' + '\n' +
        '  <prm-search-bar (search-event)="ctrl.onSearchBarSearchEvent($event)" class="animate-search-bar"></prm-search-bar>' + '\n' +
        '  <prm-spinner ng-if="ctrl.searchInProgress" class="half-transparent no-text" layout="row" layout-align="center center"></prm-spinner>' + '\n' +
        '</div>' + '\n' +
        '<ui-view></ui-view>' + '\n' +
        '<prm-explore-main-after parent-ctrl="ctrl"></prm-explore-main-after>' + '\n'
      );
    }]);

})();
```

Could you let us know what the correct way is to inject our own header block into the template?

Thank you!

**Comment by noamamit92** [comment]
We created the https://github.com/ExLibrisGroup/primo-explore-devenv 
and the concept of the *-after hooks to allow adding widgets which are independent , so using it to change an existing template is really not the intention

What I suggest you do:

1. add a link via the BO in the main menu tile
2. hook into the prm-topbar-after and define an alternative top bar (relying on the OTB html in the topbar), Then by css hide the prm-topbar and expose the prm-top-bar-after

**Comment by gquach** [comment]
@noamamit92 Thanks very much, we'll look into doing what you suggested!

**Comment by antrez770** [comment]
Hi How can I add cutom JS- files or code to Primo?
Is somebody knows about Accessibility menu plugin for Primo? 
Thank You.
