### ISSUE TITLE
Different custom.js file in UI template package (from Primo BO)

### ISSUE THREAD

**Issue by apetryk** [ExLibrisGroup/primo-explore-package#4]
Hi,

The custom.js file in the UI template package (from Primo BO) is slightly different from the one available in this repo.  This difference unfortunately prevents any JS customization.  The problem is with the last line:

Repo version (correct):

})();

Package version (incorrect):

})

I'm posting this here in case anyone comes across this issue.

**Comment by noamamit92** [comment]
Fixed for the Primo February 2017 release - in the meantime - the best solution is to use the package from this repository
