### ISSUE TITLE
app-css error

### ISSUE THREAD

**Issue by lajamie** [ExLibrisGroup/primo-explore-package#5]
As directed in https://github.com/ExLibrisGroup/primo-explore-package/blob/master/VIEW_CODE/css/README.md, running this command:

`gulp app-css --view <your-view/folder code>`

gave the following status lines and then an error:

`[16:58:26] Using gulpfile ~/Workspace/primo-explore-devenv/gulpfile.js`
`[16:58:26] Starting 'app-css'...`
`[16:58:26] Starting 'extract-scss-files'...`
`http://onesearchpprd.library.nd.edu:80/primo-explore/lib/scsss.tar.gz`
`events.js:141`
`      throw er; // Unhandled 'error' event`
`      ^`
` `
`Error: incorrect header check`
`    at Zlib._handle.onerror (zlib.js:363:17)`

Other things appear to be working correctly. What should I do to fix this?

**Comment by noamamit92** [comment]
What primo version are you running?

**Comment by lajamie** [comment]
Oh, it looks like we're on the May 2016 release. I thought we were on the August release. Sorry about that!
