### ISSUE TITLE
Taking Pull Requests?

### ISSUE THREAD

**Issue by Steve-A-Orr** [ExLibrisGroup/primo-explore-package#6]
I submitted a pull request for the [ExLibrisGroup/primo-explore-devenv](https://github.com/ExLibrisGroup/primo-explore-devenv/pull/36) repository and anticipated doing the same for this package--but don't want to bother if you're not accepting them.

I think there is some markdown formatting changes and a little more detail that can be provided in this documentation to allow developers, who are new to Primo, to catch up quickly.

**Comment by inspector71** [comment]
Fixing the broken links at the bottom of README.md would certainly help. Unsurprisingly no response from ExLibris two weeks after this issue is lodged though.

**Comment by Steve-A-Orr** [comment]
I guess I'll clean up my messes on Github. Sad that there was no response from ExLibris.

**Comment by noamamit92** [comment]
Hi @Steve-A-Orr - Sorry for not responding , we really appreciate your work on  ExLibrisGroup/primo-explore-devenv, but haven't been actively monitoring this project.

**Comment by ajtag** [comment]
@noamamit92 does that mean the other issues requests will start to get responses?

**Comment by noamamit92** [comment]
@ajtag - We will review them and start addressing them by priority
