### ISSUE TITLE
ShowDirective.txt

### ISSUE THREAD

**Issue by rurikayuki** [ExLibrisGroup/primo-explore-package#8]
I have add the content in showDirectives.txt as a bookmark. However only one "hover for id" is showed. May I know the reason?

**Comment by rurikayuki** [comment]
I have already found out the reason. 

In showDirective.txt, it finds parent-ctrl="ctrl" 
However, in primo UI code, there are only one parent-ctrl="ctrl" and others are parent-ctrl="$ctrl"

**Comment by ShoulM** [comment]
Fixed! Please see https://github.com/ExLibrisGroup/primo-explore-package/blob/master/VIEW_CODE/showDirectives.txt for updated script.
